### ISSUE TITLE
creation of the "shop" to exchange rainbows to prizes

### ISSUE THREAD

**Issue by karina-klinkeviciute** [karina-klinkeviciute/rainbow-challenge-front#14]
# Rainbow shop

Rainbows (points) can be exchanged to prizes. For this we need a prize "shop" which is called "Rainbow shop". 

In this screen User sees a list of prizes and also the amount of "active" rainbows that they can exchange into prizes. 

## List of prizes

We need to show a list of prizes. Each prize has this information:
* name, 
* photo 
* description
* price in rainbows 
* amount remaining. 

Visually they should be scrollable to the sides or up (probably best to the sides).

Endpoint: https://rainbowchallenge.lt/api/schema/swagger-ui/#/api/api_results_available_prize_list 

It should be scrolled (preferably horizontally but suggestions are welcome)

If a user decides to take one of those prizes, they can touch on it and get to the exchange window 

## Prize exchange

After User choses a prize in the prize list, they are brought to this screen.

endpoint for a prize:

https://rainbowchallenge.lt/api/schema/swagger-ui/#/api/api_results_available_prize_retrieve

Information to be displayed. :

    * photo/illustration if there is one,
    * name
    * amount (available)
    * price in rainbows

It has to have a field for the desired amount ("Pageidaujamas kiekis") of this prize and a button "Order" ("Užsakyti")

After pressing the button, a POST request has to be made to the endpoint for claimed prize https://rainbowchallenge.lt/api/schema/swagger-ui/#/api/api_results_claimed_prize_create.

On the backend, the availability of the prizes is being checked, together with the amount of rainbows. If there isn't enough of this prize available (let's say someone else took some a short moment ago), it will return an error. Also, if the user doesn't have enough of rainbow for this/these prizes, it will return an error too.

If there are no errors, a simple screen needs to be shown that says "Your request was sent, we will contact you by email and will let you know how you can receive it" ("Užsakymas išsiųstas. Susisieksim su tavim el. paštu ir pranešim, kaip atsiimti prizus.")

Then there's a "back" button which takes user to the list of prizes.

Please talk to Ieva @tyte  about the designs

**Comment by tyte** [comment]
Illustration for shop can be found in assets/images/dialogs folder.
