### ISSUE TITLE
Refactor home page to use TabBarView

### ISSUE THREAD

**Issue by ignasbagdonas** [karina-klinkeviciute/rainbow-challenge-front#51]
Now we have simple bottomNavigationBar widget and on every tab click pushing new page. It's not correct, we should use  TabBarView instead.

**Comment by Colin-Stark** [comment]
I can help with that

**Comment by karina-klinkeviciute** [comment]
> 
@Colin-Stark 
this has already been done. Do you want to help with other issues on this project?

**Comment by Colin-Stark** [comment]
Yes, as much as I can

**Comment by karina-klinkeviciute** [comment]
> Yes, as much as I can

@Colin-Stark please send me an email at karina.klinkeviciute@gmail.com

**Comment by Colin-Stark** [comment]
Done
